/// Arabic (RTL) translations.
const Map<String, String> stringsAr = {
  // ── App / navigation ─────────────────────────────────────────────
  'appName': 'فوكس OBD2 سكانر',
  'navHome': 'الرئيسية',
  'navDashboard': 'لوحة التحكم',
  'navDtc': 'أكواد الأخطاء',
  'navHistory': 'السجل',
  'navReports': 'التقارير',
  'navSettings': 'الإعدادات',

  // ── Common ───────────────────────────────────────────────────────
  'ok': 'حسناً',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'delete': 'حذف',
  'retry': 'إعادة المحاولة',
  'save': 'حفظ',
  'close': 'إغلاق',
  'error': 'خطأ',
  'success': 'نجاح',
  'loading': 'جارٍ التحميل...',
  'online': 'متصل بالإنترنت',
  'offline': 'غير متصل بالإنترنت',
  'min': 'الأدنى',
  'max': 'الأعلى',
  'avg': 'المتوسط',
  'date': 'التاريخ',
  'time': 'الوقت',
  'from': 'من',
  'to': 'إلى',
  'today': 'اليوم',
  'share': 'مشاركة',
  'all': 'الكل',
  'none': 'لا شيء',
  'on': 'مفعّل',
  'off': 'مطفأ',

  // ── Home / connection ────────────────────────────────────────────
  'scanDevices': 'البحث عن الأجهزة',
  'scanning': 'جارٍ البحث...',
  'availableDevices': 'الأجهزة المتاحة',
  'pairedDevices': 'الأجهزة المقترنة',
  'favoriteDevices': 'الأجهزة المفضلة',
  'noDevices': 'لم يتم العثور على أجهزة',
  'noDevicesHint': 'تأكد من توصيل جهاز OBD2 بالسيارة وتشغيله.',
  'connect': 'اتصال',
  'disconnect': 'قطع الاتصال',
  'connected': 'متصل',
  'disconnected': 'غير متصل',
  'connecting': 'جارٍ الاتصال...',
  'initializing': 'جارٍ تهيئة الجهاز...',
  'connectedTo': 'متصل بـ',
  'connectionFailed': 'فشل الاتصال. تحقق من الجهاز وحاول مرة أخرى.',
  'addFavorite': 'إضافة إلى المفضلة',
  'removeFavorite': 'إزالة من المفضلة',
  'lastConnected': 'آخر اتصال',
  'connectionCount': 'عدد مرات الاتصال',
  'vehicleInfo': 'معلومات السيارة',
  'protocol': 'البروتوكول',
  'adapterVoltage': 'جهد الجهاز',
  'bluetoothOff': 'البلوتوث مطفأ',
  'enableBluetooth': 'تفعيل البلوتوث',
  'permissionsNeeded': 'أذونات البلوتوث مطلوبة للبحث عن الأجهزة.',
  'grantPermissions': 'منح الأذونات',
  'demoMode': 'الوضع التجريبي',
  'demoModeDesc': 'جرّب التطبيق ببيانات سيارة محاكاة (بدون جهاز).',
  'goToDashboard': 'فتح لوحة التحكم',

  // ── Dashboard ────────────────────────────────────────────────────
  'liveData': 'بيانات حية',
  'engineTemp': 'حرارة المحرك',
  'rpm': 'دورات المحرك',
  'speed': 'السرعة',
  'fuelLevel': 'مستوى الوقود',
  'batteryVoltage': 'البطارية',
  'throttle': 'الخنق',
  'oxygenSensor': 'حساس الأكسجين',
  'intakeTemp': 'هواء السحب',
  'checkEngine': 'فحص المحرك',
  'notConnected': 'غير متصل',
  'connectFirst': 'اتصل بجهاز OBD2 من الشاشة الرئيسية أولاً.',
  'kmh': 'كم/س',
  'celsius': '°م',
  'volts': 'فولت',
  'percent': '٪',
  'batteryHealthy': 'سليمة',
  'batteryLow': 'منخفضة',
  'batteryOvercharge': 'مرتفعة',

  // ── DTC ──────────────────────────────────────────────────────────
  'dtcTitle': 'أكواد الأعطال التشخيصية',
  'readCodes': 'قراءة الأكواد',
  'readingCodes': 'جارٍ قراءة الأكواد...',
  'clearCodes': 'حذف الأكواد',
  'clearingCodes': 'جارٍ حذف الأكواد...',
  'clearConfirmTitle': 'حذف جميع أكواد الأعطال؟',
  'clearConfirmBody':
      'سيتم إرسال الأمر Mode 04 إلى كمبيوتر السيارة: يمسح الأكواد المخزنة '
      'ويطفئ لمبة فحص المحرك. ستعود الأكواد إذا استمر العطل. هل تريد المتابعة؟',
  'clearSuccess': 'تم حذف أكواد الأعطال بنجاح.',
  'clearFailed': 'فشل حذف الأكواد. حاول مرة أخرى والمحرك مطفأ.',
  'noCodes': 'لا توجد أكواد أعطال',
  'noCodesDesc': 'ممتاز! لا توجد أعطال مسجلة في كمبيوتر السيارة حالياً.',
  'codesFound': 'كود',
  'statusConfirmed': 'مؤكد',
  'statusPending': 'معلق',
  'statusPermanent': 'دائم',
  'severity': 'الخطورة',
  'severityCritical': 'حرجة',
  'severityModerate': 'متوسطة',
  'severityLow': 'منخفضة',
  'detectedOn': 'تاريخ الاكتشاف',
  'firstSeen': 'أول ظهور',
  'lastSeen': 'آخر ظهور',
  'unknownCode': 'كود غير معروف — راجع دليل الصيانة.',

  // ── History ──────────────────────────────────────────────────────
  'historyTitle': 'السجل والبيانات',
  'filterByDate': 'تصفية حسب التاريخ',
  'allTime': 'كل الفترات',
  'last7Days': 'آخر 7 أيام',
  'last30Days': 'آخر 30 يوماً',
  'records': 'سجل',
  'noRecords': 'لا توجد سجلات بعد',
  'noRecordsDesc': 'اتصل بسيارتك وسيتم تسجيل البيانات تلقائياً.',
  'tempChart': 'درجة حرارة المحرك',
  'rpmChart': 'توزيع دورات المحرك',
  'speedChart': 'السرعة',
  'exportDrive': 'تصدير إلى Google Drive',
  'shareWhatsApp': 'مشاركة عبر واتساب',
  'deleteData': 'حذف البيانات',
  'deleteConfirmTitle': 'حذف جميع السجلات؟',
  'deleteConfirmBody':
      'سيتم حذف جميع سجلات OBD2 المخزنة نهائياً من هذا الجهاز. '
      'لا يمكن التراجع عن هذا الإجراء.',
  'deleteSuccess': 'تم حذف السجلات.',
  'loadMore': 'تحميل المزيد',
  'exportCsv': 'تصدير CSV',
  'exportJson': 'تصدير JSON',
  'exportSuccess': 'تم التصدير بنجاح.',
  'exportFailed': 'فشل التصدير.',
  'queuedOffline':
      'أنت غير متصل بالإنترنت — تمت جدولة التصدير وسيتم تنفيذه عند عودة الاتصال.',
  'syncPending': 'بانتظار المزامنة',

  // ── Reports ──────────────────────────────────────────────────────
  'reportsTitle': 'التقارير',
  'dailyReport': 'التقرير اليومي',
  'generateReport': 'إنشاء تقرير اليوم',
  'generating': 'جارٍ إنشاء التقرير...',
  'reportReady': 'التقرير جاهز',
  'noReports': 'لا توجد تقارير بعد',
  'noReportsDesc':
      'تُنشأ التقارير اليومية تلقائياً في الوقت المحدد، أو أنشئ تقريراً الآن.',
  'performanceSummary': 'ملخص الأداء',
  'avgTemp': 'متوسط الحرارة',
  'maxTemp': 'أعلى حرارة',
  'minTemp': 'أدنى حرارة',
  'avgRpm': 'متوسط الدورات',
  'maxRpm': 'أعلى دورات',
  'avgFuel': 'متوسط الوقود',
  'minFuel': 'أدنى وقود',
  'maxSpeed': 'أعلى سرعة',
  'newCodes': 'أكواد جديدة',
  'recommendations': 'التوصيات',
  'saveToDrive': 'حفظ في Google Drive',
  'viewPdf': 'عرض PDF',
  'reportFor': 'تقرير يوم',
  'recOverheat':
      'تجاوزت حرارة المحرك 110°م — افحص سائل التبريد والرادياتير والثرموستات.',
  'recHighRpm':
      'تم رصد دورات محرك مرتفعة لفترات طويلة — يُنصح بتسارع أهدأ لتقليل الإجهاد.',
  'recLowFuel': 'انخفض الوقود عن 15٪ — تجنب القيادة بوقود منخفض لحماية المضخة.',
  'recDtc': 'تم اكتشاف أكواد أعطال جديدة — راجع شاشة أكواد الأخطاء.',
  'recBattery': 'جهد البطارية خارج النطاق السليم — افحص البطارية والدينامو.',
  'recAllGood': 'كل شيء يبدو جيداً. حافظ على الصيانة الدورية!',

  // ── Settings ─────────────────────────────────────────────────────
  'settingsTitle': 'الإعدادات',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'English',
  'appearance': 'المظهر',
  'darkMode': 'داكن',
  'lightMode': 'فاتح',
  'googleDrive': 'Google Drive',
  'signIn': 'تسجيل الدخول',
  'signOut': 'تسجيل الخروج',
  'signedInAs': 'مسجّل الدخول باسم',
  'notSignedIn': 'غير مسجّل الدخول',
  'driveDesc': 'نسخ احتياطي اختياري لبياناتك وتقاريرك إلى حسابك الخاص في Drive.',
  'lastBackup': 'آخر نسخة احتياطية',
  'notifications': 'الإشعارات',
  'tempAlerts': 'تنبيهات حرارة المحرك',
  'dtcAlerts': 'تنبيهات الأكواد الجديدة',
  'fuelAlerts': 'تنبيهات الوقود المنخفض',
  'dailyReportNotif': 'إشعار التقرير اليومي',
  'reportTime': 'وقت التقرير اليومي',
  'database': 'قاعدة البيانات',
  'dbSize': 'حجم قاعدة البيانات',
  'recordCount': 'عدد السجلات المخزنة',
  'about': 'حول التطبيق',
  'version': 'الإصدار',
  'privacy': 'الخصوصية',
  'privacyDesc':
      'جميع البيانات تبقى على جهازك. لا يتم رفع أي شيء إلا إذا اخترت التصدير '
      'إلى حسابك الخاص في Google Drive. بدون إعلانات وبدون تتبع.',

  // ── Alerts / notifications ───────────────────────────────────────
  'tempAlertTitle': '⚠️ تنبيه! درجة حرارة المحرك عالية جداً',
  'tempAlertBody': 'درجة حرارة المحرك مرتفعة بشكل خطير',
  'dtcAlertTitle': '⚠️ تم اكتشاف خطأ جديد',
  'dtcAlertBody': 'تم اكتشاف كود عطل تشخيصي جديد',
  'fuelAlertTitle': '🛢️ تنبيه: مستوى الوقود منخفض',
  'fuelAlertBody': 'مستوى الوقود منخفض جداً',
  'reportNotifTitle': '📋 التقرير اليومي جاهز',
  'reportNotifBody': 'تم إنشاء تقرير سيارتك اليومي. اضغط للعرض.',
};
