/// English (LTR) translations.
const Map<String, String> stringsEn = {
  // ── App / navigation ─────────────────────────────────────────────
  'appName': 'Focus OBD2 Scanner',
  'navHome': 'Home',
  'navDashboard': 'Dashboard',
  'navDtc': 'DTC Codes',
  'navHistory': 'History',
  'navReports': 'Reports',
  'navSettings': 'Settings',

  // ── Common ───────────────────────────────────────────────────────
  'ok': 'OK',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'delete': 'Delete',
  'retry': 'Retry',
  'save': 'Save',
  'close': 'Close',
  'error': 'Error',
  'success': 'Success',
  'loading': 'Loading...',
  'online': 'Online',
  'offline': 'Offline',
  'min': 'Min',
  'max': 'Max',
  'avg': 'Avg',
  'date': 'Date',
  'time': 'Time',
  'from': 'From',
  'to': 'To',
  'today': 'Today',
  'share': 'Share',
  'all': 'All',
  'none': 'None',
  'on': 'ON',
  'off': 'OFF',

  // ── Home / connection ────────────────────────────────────────────
  'scanDevices': 'Scan for devices',
  'scanning': 'Scanning...',
  'availableDevices': 'Available devices',
  'pairedDevices': 'Paired devices',
  'favoriteDevices': 'Favorite devices',
  'noDevices': 'No devices found',
  'noDevicesHint': 'Make sure your OBD2 adapter is plugged in and powered.',
  'connect': 'Connect',
  'disconnect': 'Disconnect',
  'connected': 'Connected',
  'disconnected': 'Disconnected',
  'connecting': 'Connecting...',
  'initializing': 'Initializing adapter...',
  'connectedTo': 'Connected to',
  'connectionFailed': 'Connection failed. Check the adapter and try again.',
  'addFavorite': 'Add to favorites',
  'removeFavorite': 'Remove from favorites',
  'lastConnected': 'Last connected',
  'connectionCount': 'Connections',
  'vehicleInfo': 'Vehicle info',
  'protocol': 'Protocol',
  'adapterVoltage': 'Adapter voltage',
  'bluetoothOff': 'Bluetooth is off',
  'enableBluetooth': 'Enable Bluetooth',
  'permissionsNeeded': 'Bluetooth permissions are required to scan.',
  'grantPermissions': 'Grant permissions',
  'demoMode': 'Demo mode',
  'demoModeDesc': 'Try the app with simulated vehicle data (no adapter).',
  'goToDashboard': 'Open Dashboard',

  // ── Dashboard ────────────────────────────────────────────────────
  'liveData': 'Live data',
  'engineTemp': 'Engine temp',
  'rpm': 'RPM',
  'speed': 'Speed',
  'fuelLevel': 'Fuel level',
  'batteryVoltage': 'Battery',
  'throttle': 'Throttle',
  'oxygenSensor': 'O₂ sensor',
  'intakeTemp': 'Intake air',
  'checkEngine': 'Check engine',
  'notConnected': 'Not connected',
  'connectFirst': 'Connect to an OBD2 adapter from the Home screen first.',
  'kmh': 'km/h',
  'celsius': '°C',
  'volts': 'V',
  'percent': '%',
  'batteryHealthy': 'Healthy',
  'batteryLow': 'Low',
  'batteryOvercharge': 'High',

  // ── DTC ──────────────────────────────────────────────────────────
  'dtcTitle': 'Diagnostic Trouble Codes',
  'readCodes': 'Read codes',
  'readingCodes': 'Reading codes...',
  'clearCodes': 'Clear codes',
  'clearingCodes': 'Clearing codes...',
  'clearConfirmTitle': 'Clear all trouble codes?',
  'clearConfirmBody':
      'This sends Mode 04 to the ECU: it erases stored codes, freeze frames '
      'and turns off the check-engine light. Codes will return if the fault '
      'persists. Continue?',
  'clearSuccess': 'Trouble codes cleared successfully.',
  'clearFailed': 'Failed to clear codes. Try again with the engine off.',
  'noCodes': 'No trouble codes',
  'noCodesDesc': 'Great! No faults are currently reported by the ECU.',
  'codesFound': 'codes found',
  'statusConfirmed': 'Confirmed',
  'statusPending': 'Pending',
  'statusPermanent': 'Permanent',
  'severity': 'Severity',
  'severityCritical': 'Critical',
  'severityModerate': 'Moderate',
  'severityLow': 'Low',
  'detectedOn': 'Detected on',
  'firstSeen': 'First seen',
  'lastSeen': 'Last seen',
  'unknownCode': 'Unknown code — consult a service manual.',

  // ── History ──────────────────────────────────────────────────────
  'historyTitle': 'History & Data',
  'filterByDate': 'Filter by date',
  'allTime': 'All time',
  'last7Days': 'Last 7 days',
  'last30Days': 'Last 30 days',
  'records': 'records',
  'noRecords': 'No records yet',
  'noRecordsDesc': 'Connect to your car and data will be logged automatically.',
  'tempChart': 'Engine temperature',
  'rpmChart': 'RPM distribution',
  'speedChart': 'Speed',
  'exportDrive': 'Export to Google Drive',
  'shareWhatsApp': 'Share via WhatsApp',
  'deleteData': 'Delete data',
  'deleteConfirmTitle': 'Delete all records?',
  'deleteConfirmBody':
      'All stored OBD2 records will be permanently deleted from this device. '
      'This cannot be undone.',
  'deleteSuccess': 'Records deleted.',
  'loadMore': 'Load more',
  'exportCsv': 'Export CSV',
  'exportJson': 'Export JSON',
  'exportSuccess': 'Export completed.',
  'exportFailed': 'Export failed.',
  'queuedOffline':
      'You are offline — the export was queued and will sync when online.',
  'syncPending': 'Pending sync',

  // ── Reports ──────────────────────────────────────────────────────
  'reportsTitle': 'Reports',
  'dailyReport': 'Daily report',
  'generateReport': 'Generate today\'s report',
  'generating': 'Generating report...',
  'reportReady': 'Report ready',
  'noReports': 'No reports yet',
  'noReportsDesc':
      'Daily reports are generated automatically at the scheduled time, or '
      'generate one now.',
  'performanceSummary': 'Performance summary',
  'avgTemp': 'Avg temp',
  'maxTemp': 'Max temp',
  'minTemp': 'Min temp',
  'avgRpm': 'Avg RPM',
  'maxRpm': 'Max RPM',
  'avgFuel': 'Avg fuel',
  'minFuel': 'Min fuel',
  'maxSpeed': 'Max speed',
  'newCodes': 'New codes',
  'recommendations': 'Recommendations',
  'saveToDrive': 'Save to Google Drive',
  'viewPdf': 'View PDF',
  'reportFor': 'Report for',
  'recOverheat':
      'Engine temperature exceeded 110°C — check coolant level, radiator and thermostat.',
  'recHighRpm':
      'Sustained high RPM detected — consider gentler acceleration to reduce wear.',
  'recLowFuel': 'Fuel dropped below 15% — avoid running on low fuel to protect the pump.',
  'recDtc': 'New trouble codes were detected — review the DTC screen.',
  'recBattery': 'Battery voltage was outside the healthy range — test the battery/alternator.',
  'recAllGood': 'Everything looks good. Keep up the regular maintenance!',

  // ── Settings ─────────────────────────────────────────────────────
  'settingsTitle': 'Settings',
  'language': 'Language',
  'arabic': 'العربية',
  'english': 'English',
  'appearance': 'Appearance',
  'darkMode': 'Dark',
  'lightMode': 'Light',
  'googleDrive': 'Google Drive',
  'signIn': 'Sign in',
  'signOut': 'Sign out',
  'signedInAs': 'Signed in as',
  'notSignedIn': 'Not signed in',
  'driveDesc': 'Optional backup of your data and reports to your own Drive.',
  'lastBackup': 'Last backup',
  'notifications': 'Notifications',
  'tempAlerts': 'Engine temperature alerts',
  'dtcAlerts': 'New trouble code alerts',
  'fuelAlerts': 'Low fuel alerts',
  'dailyReportNotif': 'Daily report notification',
  'reportTime': 'Daily report time',
  'database': 'Database',
  'dbSize': 'Database size',
  'recordCount': 'Stored records',
  'about': 'About',
  'version': 'Version',
  'privacy': 'Privacy',
  'privacyDesc':
      'All data stays on your device. Nothing is uploaded unless you '
      'explicitly export to your own Google Drive. No ads, no tracking.',

  // ── Alerts / notifications ───────────────────────────────────────
  'tempAlertTitle': '⚠️ High engine temperature!',
  'tempAlertBody': 'Engine temperature is critically high',
  'dtcAlertTitle': '⚠️ New trouble code detected',
  'dtcAlertBody': 'A new diagnostic trouble code was detected',
  'fuelAlertTitle': '🛢️ Low fuel',
  'fuelAlertBody': 'Fuel level is very low',
  'reportNotifTitle': '📋 Daily report ready',
  'reportNotifBody': 'Your daily vehicle report has been generated. Tap to view.',
};
